services:
  keras:
    container_name: keras
    image: ghcr.io/dendik-creation/keras:${IMAGE_TAG:-latest}
    pull_policy: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
